version: "3"
services:
  mongo:
    image: "mongo"
    container_name: mongo
    ports:
      - "8080:27017"
    volumes:
      - ./mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend

    ports:
      - "5000:5000"

    depends_on:
      - mongo
    env_file:
      - "./backend/.env.prod"
    

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - "./frontend/.env.prod"
